kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: iris-ssd-storageclass
parameters:
  type: cbs
provisioner: cloud.tencent.com/qcloud-cbs
volumeBindingMode: WaitForFirstConsumer
